spring:
  application:
    name: OrderFlow
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop # не корректный подход
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

token:
  signing:
    key: "dGhpcyBpc19hX3ZlcnlfbG9uZ19hbmRfc2VjdXJlX3NlY3JldF9rZXlfZm9yX2p3dA=="